Feature getby
seabay-hratx42-fec/reviews pull request #3
Opened 2019-07-11 20:17 UTC by mileszander

2019-07-11 20:18 UTC, mileszander commented
This is to pull my db data by id, also populated my db with dummy data

2019-07-11 20:51 UTC, rcalimlim commented on db/userSchema.js
> +const connectionString = "mongodb+srv://root:root@reviews-y8owi.mongodb.net/test?retryWrites=true&w=majority"
uh oh

2019-07-11 20:52 UTC, rcalimlim requested changes
Should probably remove your db pass since you're already using .dotenv

2019-07-12 15:14 UTC, mileszander commented on db/userSchema.js
> +const connectionString = "mongodb+srv://root:root@reviews-y8owi.mongodb.net/test?retryWrites=true&w=majority"
:D

2019-07-12 15:32 UTC, mileszander commented on db/userSchema.js
> +const connectionString = "mongodb+srv://root:root@reviews-y8owi.mongodb.net/test?retryWrites=true&w=majority"
Updated to be super secure

2019-07-12 15:32 UTC, merged